remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title                    : "VentureBeyond"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Craig Ansell"
description              : "An amazing website."
url: "https://craigansell.github.io/venturebeyond"
atom_feed:
  hide: true
author:
  name     : "Your Name"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Somewhere, USA"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
