title: Venture Beyond
logo: /assets/img/logo-color.png
#description: Freelance Hill Walking and Climbing Instructor
show_downloads: true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: jekyll-theme-architect
plugins: jekyll-include-cache
