title: Venture Beyond
logo: /assets/img/logo-color.png
#description: Freelance Hill Walking and Climbing Instructor
show_downloads: true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
#new
header:
  image: /assets/images/IMG_3294.jpeg
